name: Build Test

on:
  push:
    branches:
      - '**'  # Executa para qualquer branch
    tags: []  # Não executa para tags
  pull_request:
    branches:
      - '**'  # Executa para qualquer branch

jobs:
  build_test:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'
          cache: 'yarn'
      - name: Clear Yarn Cache
        run: yarn cache clean
      - name: Install dependencies
        working-directory: ./src
        run: yarn install --frozen-lockfile
      - name: Build Bundles
        working-directory: ./src
        run: yarn build
