name: Build and Release

on:
    push:
        tags:
            - "v*.*.*"
jobs:
    build_and_release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "16" # versão suportada pelo FiveM

            - name: Install dependencies
              working-directory: ./src
              run: npm install

            - name: Build project
              working-directory: ./src
              run: npm run build

            - name: Get tag version without "v"
              id: get_version
              run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

            - name: Update version in file
              run: |
                  sed -i "s/MRIQBOX_VERSION/${{ env.VERSION }}/g" fxmanifest.lua

            - name: Create Release
              uses: softprops/action-gh-release@v1
              with:
                  files: . # ajuste o caminho conforme necessário

                  exclude: |
                      ./src/**
                      .gitignore
                      .editorconfig
                      .github/**
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
            - name: Get release commits
              run: |
                CURRENT_TAG=${{ github.event.release.tag_name }}
                COMMITS=$(git log $CURRENT_TAG --pretty=format:"- %s")
                echo "COMMITS=$COMMITS" >> $GITHUB_ENV

            - name: Post to Discord (with embed)
              env:
                DISCORD_WEBHOOK_URL: ${{ secrets.UPDATE_DISCORD_WEBHOOK }}
                COMMITS: ${{ env.COMMITS }}
                RELEASE_URL: ${{ github.event.release.html_url }}
                RELEASE_TAG: ${{ github.event.release.tag_name }}
                RELEASE_NAME: ${{ github.event.release.name }}
              run: |
                EMBED_DATA='{
                    "embeds": [{
                    "title": "Nova versão disponível: '"${env.VERSION}"',
                    "url": "'"${RELEASE_URL}"'",
                    "color": 4243543,
                    "fields": [{
                        "name": "O que há de novo?",
                        "value": "'"${COMMITS}"'"
                    }],
                    "footer": {
                        "text": "MRI QBOX",
                        "icon_url": "https://assets.mriqbox.com.br/branding/logo96.png"
                    },
                    "timestamp": "'"$(date --utc +%Y-%m-%dT%H:%M:%SZ)"'"
                    }]
                }'
                curl -H "Content-Type: application/json" \
                    -d "$EMBED_DATA" \
                    $DISCORD_WEBHOOK_URL

