name: Build and Release

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    build_and_release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "16" # versão suportada pelo FiveM

            - name: Install dependencies
              working-directory: ./src
              run: npm install

            - name: Build project
              working-directory: ./src
              run: npm run build

            - name: Get tag version without "v"
              id: get_version
              run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

            - name: Update version in file
              run: |
                  sed -i "s/MRIQBOX_VERSION/${{ env.VERSION }}/g" fxmanifest.lua

            # Criar o arquivo ZIP excluindo os diretórios/arquivos especificados
            - name: Create ZIP file
              run: |
                  ZIP_NAME="${{ github.repository }}.zip"
                  find . -path "**/node_modules" -prune -o -print | zip -r $ZIP_NAME -@
              shell: bash

            - name: Create Release
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      *.zip
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
