name: Build and Release

on:
    push:
        tags:
            - "v*.*.*"

permissions:
    contents: write
    actions: write

jobs:
    build_and_release:
        runs-on: ubuntu-latest
        outputs:
            version: ${{ steps.get_project_information.outputs.version }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "16"

            - name: Install dependencies
              working-directory: ./src
              run: npm install

            - name: Build project
              working-directory: ./src
              run: npm run build

            - name: Get commit messages, version, and repository description
              id: get_project_information
              run: |
                  # Obtemos a tag anterior se ela existir
                  LAST_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")

                  # Definimos a versão a partir da tag atual
                  CURRENT_TAG="${GITHUB_REF#refs/tags/}"

                  if [ -n "$LAST_TAG" ]; then
                    # Se houver uma tag anterior, capturamos os commits entre a tag anterior e a tag atual
                    COMMITS=$(git log $LAST_TAG..$GITHUB_SHA --oneline --pretty=format:"%h %s")
                  else
                    # Se não houver tags anteriores (primeira tag), capturamos todos os commits
                    COMMITS=$(git log --oneline --pretty=format:"%h %s")
                  fi

                  # Salva os commits e a descrição em um arquivo
                  echo "$COMMITS" > ./release_body.txt
                  echo "version=$CURRENT_TAG" >> $GITHUB_OUTPUT

            - name: Update version in file
              run: |
                  sed -i "s/MRIQBOX_VERSION/${{ steps.get_project_information.outputs.version }}/g" fxmanifest.lua

            - name: Create ZIP file
              run: |
                  mkdir -p release/${{ github.event.repository.name }}
                  mkdir -p release/${{ github.event.repository.name }}/modules
                  mkdir -p release/${{ github.event.repository.name }}/web-side
                  cp fxmanifest.lua release/${{ github.event.repository.name }}
                  cp -r modules/**/* release/${{ github.event.repository.name }}/modules
                  cp -r web-side/**/* release/${{ github.event.repository.name }}/web-side
                  cd release
                  zip -r "${{ github.event.repository.name }}.zip" "${{ github.event.repository.name }}"

            - name: Generate Release
              uses: comnoco/create-release-action@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              id: release
              with:
                  tag_name: "${{ steps.get_project_information.outputs.version }}"
                  release_name: "${{ steps.get_project_information.outputs.version }}"
                  body_path: ./release_body.txt
                  draft: false
                  prerelease: false

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: "${{ github.event.repository.name }}.zip"
                  path: release/${{ github.event.repository.name }}.zip

    post_to_discord:
        needs: build_and_release
        runs-on: ubuntu-latest
        steps:
            - name: Post to Discord (with embed)
              env:
                  DISCORD_WEBHOOK_URL: ${{ secrets.UPDATE_DISCORD_WEBHOOK }}
                  RELEASE_URL: https://github.com/${{ github.repository }}/releases/latest
                  RELEASE_TAG: ${{ github.ref_name }}
                  RELEASE_AUTHOR: ${{ github.actor }}
              run: |
                  # Obtenha a descrição do repositório diretamente aqui
                  REPO_DESCRIPTION=$(curl -s https://api.github.com/repos/${{ github.repository }} | jq -r .description)

                  # Crie o JSON para o embed do Discord
                  EMBED_DATA='{
                      "embeds": [{
                      "title": "Nova versão disponível: '"${RELEASE_TAG}"'",
                      "url": "'"${RELEASE_URL}"'",
                      "description": "Description",
                      "color": 4243543,
                      "footer": {
                          "text": "MRI QBOX - Liberado por: '"${RELEASE_AUTHOR}"'",
                          "icon_url": "https://assets.mriqbox.com.br/branding/logo96.png"
                      },
                      "timestamp": "'"$(date --utc +%Y-%m-%dT%H:%M:%SZ)"'"
                      }]
                  }'

                  echo "$EMBED_DATA"

                  # Envie o webhook para o Discord
                  curl -H "Content-Type: application/json" \
                      -d "$EMBED_DATA" \
                      $DISCORD_WEBHOOK_URL
