name: Post Release to Discord

on:
  release:
    types: [published]

jobs:
  post_to_discord:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get commit messages
      id: get_commit_messages
      run: |
        COMMITS=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
        "https://api.github.com/repos/${{ github.repository }}/compare/${{ github.event.release.tag_name }}^...${{ github.event.release.tag_name }}" \
        | jq -r '.commits[].commit.message')

    - name: Post to Discord (with embed)
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.UPDATE_DISCORD_WEBHOOK }}
        COMMITS: ${{ env.COMMITS }}
        RELEASE_URL: ${{ github.event.release.html_url }}
        RELEASE_TAG: ${{ github.event.release.tag_name }}
        RELEASE_NAME: ${{ github.event.release.name }}
      run: |
        EMBED_DATA='{
            "embeds": [{
            "title": "Nova versão disponível: '"${RELEASE_TAG}"'",
            "url": "'"${RELEASE_URL}"'",
            "color": 4243543,
            "fields": [{
                "name": "O que há de novo?",
                "value": "'"${COMMITS}"'"
            }],
            "footer": {
                "text": "MRI QBOX",
                "icon_url": "https://assets.mriqbox.com.br/branding/logo96.png"
            },
            "timestamp": "'"$(date --utc +%Y-%m-%dT%H:%M:%SZ)"'"
            }]
        }'
        curl -H "Content-Type: application/json" \
            -d "$EMBED_DATA" \
            $DISCORD_WEBHOOK_URL
